modelname: BaseFeatureExtractor
_target_: src.model.base_network.BaseFeatureExtractor

descriptor_size: 16
threshold: 0.2
pretrained_weight: ${machine.root_dir}/pretrained/moco_v2_800ep_pretrain.pth

# config_optim
lr: 0.01
weight_decay: 0.0005
warm_up_steps: 1000
log_interval: 1000
log_dir: ${save_dir}/media
use_all_gather: false
