modelname: FeatureExtractor
_target_: src.model.network.FeatureExtractor

descriptor_size: 8
threshold: 0.2
pretrained_weight: ${machine.root_dir}/pretrained/moco_v2_800ep_pretrain.pth

# config_optim
lr: 0.0001
weight_decay: 0.0005
warm_up_steps: 1000
log_interval: 2000
log_dir: ${save_dir}/media
use_all_gather: true # for multi-gpu training with larger batch_size -> efficient for contrast learning with InfoNCE

checkpoint_path: 
